---
- hosts: all 
  tasks: 
    - name: Start docker service
      service: 
        name: docker 
        state: started
    - name: Pull image and run container
      docker_container: 
        name: devops_calc
        image: "kernelpanic77/devops-calculator:latest"
        state: started
        pull: true
        interactive: true
